export type NutrientsDtoType = {
  calories: number;
  totalFat: number;
  transFat: number;
  saturatedFat: number;
  polyunsaturatedFat: number | null;
  monounsaturatedFat: number | null;
  cholesterol: number;
  sodium: number;
  totalCarbohydrates: number;
  dietaryFiber: number;
  sugars: number;
  addedSugars: number;
  sugarAlcohol: number;
  protein: number;
  calcium: number;
  iron: number;
  vitaminD: number;
  potassium: number;
  vitaminA: number;
  vitaminC: number;
  vitaminE: number;
  vitaminK: number;
  thiamin: number;
  riboflavin: number;
  niacin: number;
  vitaminB6: number;
  folicAcid: number;
  vitaminB12: number;
  biotin: number;
  pantothenicAcid: number;
  phosphorus: number;
  iodine: number;
  magnesium: number;
  zinc: number;
  selenium: number;
  copper: number;
  manganese: number;
  chromium: number;
  molybdenum: number;
  chloride: number;
  caffeine: number;
};
