env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react-hooks/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - 'eslint-plugin-no-inline-styles'
ignorePatterns: ['**/*.js']
rules:
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
  react/prop-types:
    - off
  no-inline-styles/no-inline-styles:
    - warn
