import { NutrientsDtoType } from '@shared/types/dto/Nutrients.entity';

export class DataHelper {
  public static ZEROED_NUTRIENTS: NutrientsDtoType = {
    addedSugars: 0,
    biotin: 0,
    caffeine: 0,
    calcium: 0,
    calories: 0,
    chloride: 0,
    cholesterol: 0,
    chromium: 0,
    copper: 0,
    dietaryFiber: 0,
    folicAcid: 0,
    iodine: 0,
    iron: 0,
    magnesium: 0,
    manganese: 0,
    molybdenum: 0,
    monounsaturatedFat: 0,
    niacin: 0,
    pantothenicAcid: 0,
    phosphorus: 0,
    polyunsaturatedFat: 0,
    potassium: 0,
    protein: 0,
    riboflavin: 0,
    saturatedFat: 0,
    selenium: 0,
    sodium: 0,
    sugarAlcohol: 0,
    sugars: 0,
    thiamin: 0,
    totalCarbohydrates: 0,
    totalFat: 0,
    transFat: 0,
    vitaminA: 0,
    vitaminB12: 0,
    vitaminB6: 0,
    vitaminC: 0,
    vitaminD: 0,
    vitaminE: 0,
    vitaminK: 0,
    zinc: 0,
  };
}
