export enum NotificationEnum {
  COMMENT_ON_NIB = 'COMMENT_ON_NIB',
  COMMENT_ON_RECIPE = 'COMMENT_ON_RECIPE',
  NEW_FOLLOWER = 'NEW_FOLLOWER',
  NIB_LIKED = 'NIB_LIKED',
  NIB_ON_RECIPE = 'NIB_ON_RECIPE',
  RECIPE_LIKED = 'RECIPE_LIKED',
}
